# Create new service: 'db'
# port: '5432'
# targetPort: '5432'
# type: 'ClusterIP'

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: db-deployment