# port: '5001'
# targetPort: '80'
# NodePort: '31001'


apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote
spec:
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 80
      nodePort: 31001
  type: NodePort      
  selector:
    app: result-deployment