# Create a new service: name = vote-service
# port = '5000'
# targetPort = '80'
# nodePort= '31000'
# service endpoint exposes deployment 'vote-deployment'

apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
      nodePort: 31000
  type: NodePort
  selector:     
    app: vote-deployment