# Create a deployment: name = 'vote-deployment'
# image = 'kodekloud/examplevotingapp_vote:before'
# status: 'Running'

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: vote  
spec:
  selector:
    matchLabels:
      app: vote-deployment
  template:
    metadata:
      labels:
        app: vote-deployment
    spec:
      containers:
        - name: vote-deployment
          image: kodekloud/examplevotingapp_vote:before